name: bird
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5
  get: any
  http: any
  tflite: ^1.1.2
  meta: ^1.1.8
  flutter_speed_dial: ^4.3.0

  dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/launcher_icon.png"


    # flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

    assets:
    - assets/bird_classifier.tflite
    - assets/labels.txt
    - images/
